#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -e

export DOTFILES="$HOME/.dotfiles"
cd "$DOTFILES" || exit 1

installers=( $(find . -name install.sh) );
echo "› found ${#installers[@]} installers"
for installer in ${installers[*]}; do
    read -p "... Run ${installer}? [Y/n] " response
    if [[ ! "$response" =~ ^([nN][oO]|[nN])$ ]]; then
        sh -c "$installer"
    fi
done
